import dotenv from "dotenv";

dotenv.config();

export default {
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_SYNC_SERVICE_SID: process.env.TWILIO_SYNC_SERVICE_SID || "default",
  TWILIO_VERIFICATION_SERVICE_SID: process.env.TWILIO_VERIFICATION_SERVICE_SID,
  SEGMENT_WRITEKEY: process.env.SEGMENT_WRITEKEY,
  SEGMENT_API_BASE_URL: process.env.SEGMENT_API_BASE_URL,
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  BOOTH_ID: process.env.BOOTH_ID,
  DISPENSE_DURATION: process.env.DISPENSE_DURATION,
};
